Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'seuratobject_withHTOADT_singlet_preRNAfiltering_QC_stats.txt': No such file or directory
Execution halted
